# Generated by Django 5.2.15 on 2026-07-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiummember',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
